# DATA QUALITY ASSESSMENT-  Sprocket Central Pty Ltd 

- Smith discusses KPMG’s expertise in this space (you can read more here). In particular, he speaks about how the team can effectively analyse the datasets to help Sprocket Central Pty Ltd grow its business.

- Primarily, Sprocket Central Pty Ltd needs help with its customer and transactions data. The organisation has a large dataset relating to its customers, but their team is unsure how to effectively analyse it to help optimise its marketing strategy. 

- However, in order to support the analysis, you speak to the Associate Director for some ideas and she advised that “the importance of optimising the quality of customer datasets cannot be underestimated. The better the quality of the dataset, the better chance you will be able to use it drive company growth.”

- The client provided KPMG with 3 datasets:

1.  Customer Demographic 

2.  Customer Addresses

3.  Transactions data in the past 3 months

You decide to start the preliminary data exploration and identify ways to improve the quality of Sprocket Central Pty Ltd’s data.


In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
df = pd.read_excel(r"C:\\Users\\ASUS\\KPMG_VI_New_raw_data_update_final.xlsx", sheet_name='Transactions',header=1)
df.head()

transaction_id  product_id  customer_id transaction_date  online_order  \
0               1           2         2950       2017-02-25           0.0   
1               2           3         3120       2017-05-21           1.0   
2               3          37          402       2017-10-16           0.0   
3               4          88         3135       2017-08-31           0.0   
4               5          78          787       2017-10-01           1.0   

  order_status           brand product_line product_class product_size  \
0     Approved           Solex     Standard        medium       medium   
1     Approved   Trek Bicycles     Standard        medium        large   
2     Approved      OHM Cycles     Standard           low       medium   
3     Approved  Norco Bicycles     Standard        medium       medium   
4     Approved  Giant Bicycles     Standard        medium        large   

   list_price  standard_cost  product_first_sold_date  
0       71.49          53.62                  41245.0  
1     2091.47         388.92                  41701.0  
2     1793.43         248.82                  36361.0  
3     1198.46         381.10                  36145.0  
4     1765.30         709.48                  42226.0

The raw data of the sheet "Transactions" given here is read thorugh pandas and stored in a variable "df".

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype         
---  ------                   --------------  -----         
 0   transaction_id           20000 non-null  int64         
 1   product_id               20000 non-null  int64         
 2   customer_id              20000 non-null  int64         
 3   transaction_date         20000 non-null  datetime64[ns]
 4   online_order             19640 non-null  float64       
 5   order_status             20000 non-null  object        
 6   brand                    19803 non-null  object        
 7   product_line             19803 non-null  object        
 8   product_class            19803 non-null  object        
 9   product_size             19803 non-null  object        
 10  list_price               20000 non-null  float64       
 11  standard_cost            19803 non-null  float64       
 12  product_first_sold_date  19803 n

Raw data sheet "Transactions" has 12 columns which is of object type 5, int64 3, float64 4, and datatime 1.

In [4]:
df.describe()

transaction_id   product_id   customer_id  online_order    list_price  \
count    20000.000000  20000.00000  20000.000000  19640.000000  20000.000000   
mean     10000.500000     45.36465   1738.246050      0.500458   1107.829449   
std       5773.647028     30.75359   1011.951046      0.500013    582.825242   
min          1.000000      0.00000      1.000000      0.000000     12.010000   
25%       5000.750000     18.00000    857.750000      0.000000    575.270000   
50%      10000.500000     44.00000   1736.000000      1.000000   1163.890000   
75%      15000.250000     72.00000   2613.000000      1.000000   1635.300000   
max      20000.000000    100.00000   5034.000000      1.000000   2091.470000   

       standard_cost  product_first_sold_date  
count   19803.000000             19803.000000  
mean      556.046951             38199.776549  
std       405.955660              2875.201110  
min         7.210000             33259.000000  
25%       215.140000             35667.000000  
50%       507.580000             38216.000000  
75%       795.100000             40672.000000  
max      1759.850000             42710.000000

- There are 7 numerical features:

"transaction_id	product_id	customer_id	online_order	list_price	standard_cost	product_first_sold_date"

The above table shows the median value and how the data is varied accross the "median" value.

In [5]:
df.shape

(20000, 13)

In [6]:
df['product_first_sold_date'] = pd.to_datetime(df['product_first_sold_date'], unit='s')

We can see that there are some missing values in the columns : 

'online_order', 'brand', 'product_line ', 'product_class', 'product_size', 'standard_cost', 'product_first_sold_date'

- We can also notice that the 'product_first_sold_date' column is of float datatype which has to be changed to date format.

### Data Cleaning:

In [7]:
df.isnull().sum()

transaction_id               0
product_id                   0
customer_id                  0
transaction_date             0
online_order               360
order_status                 0
brand                      197
product_line               197
product_class              197
product_size               197
list_price                   0
standard_cost              197
product_first_sold_date    197
dtype: int64

In [8]:
df.duplicated().sum()

0

### Data Description:

In [9]:
df['order_status'].value_counts()

Approved     19821
Cancelled      179
Name: order_status, dtype: int64

There are 19821 orders approved and 179 orders cancelled.

In [10]:
df.columns

Index(['transaction_id', 'product_id', 'customer_id', 'transaction_date',
       'online_order', 'order_status', 'brand', 'product_line',
       'product_class', 'product_size', 'list_price', 'standard_cost',
       'product_first_sold_date'],
      dtype='object')

In [11]:
df['product_line'].value_counts()

Standard    14176
Road         3970
Touring      1234
Mountain      423
Name: product_line, dtype: int64

In [12]:
df['brand'].value_counts()

Solex             4253
Giant Bicycles    3312
WeareA2B          3295
OHM Cycles        3043
Trek Bicycles     2990
Norco Bicycles    2910
Name: brand, dtype: int64

In [13]:
df['product_size'].value_counts()

medium    12990
large      3976
small      2837
Name: product_size, dtype: int64

# CUSTOMER DEMOGRAPHIC TABLE ANALYSIS:

In [15]:
customer_demographic = pd.read_excel(r"C:\\Users\\ASUS\\KPMG_VI_New_raw_data_update_final.xlsx", sheet_name='CustomerDemographic',header=1)
customer_demographic.head()

customer_id      first_name  last_name  gender  \
0            1         Laraine  Medendorp       F   
1            2             Eli    Bockman    Male   
2            3           Arlin     Dearle    Male   
3            4          Talbot        NaN    Male   
4            5  Sheila-kathryn     Calton  Female   

   past_3_years_bike_related_purchases        DOB               job_title  \
0                                   93 1953-10-12     Executive Secretary   
1                                   81 1980-12-16  Administrative Officer   
2                                   61 1954-01-20      Recruiting Manager   
3                                   33 1961-10-03                     NaN   
4                                   56 1977-05-13           Senior Editor   

  job_industry_category     wealth_segment deceased_indicator  \
0                Health      Mass Customer                  N   
1    Financial Services      Mass Customer                  N   
2              Property      Mass Customer                  N   
3                    IT      Mass Customer                  N   
4                   NaN  Affluent Customer                  N   

                                             default owns_car  tenure  
0                                                 "'      Yes    11.0  
1                       <script>alert('hi')</script>      Yes    16.0  
2                                2018-02-01 00:00:00      Yes    15.0  
3  () { _; } >_[$($())] { touch /tmp/blns.shellsh...       No     7.0  
4                                                NIL      Yes     8.0

The raw data of the sheet "CustomerDemographic" given here is read thorugh pandas and stored in a variable "customer_demographic".

In [16]:
customer_demographic.shape

(4000, 13)

In [17]:
customer_demographic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 13 columns):
 #   Column                               Non-Null Count  Dtype         
---  ------                               --------------  -----         
 0   customer_id                          4000 non-null   int64         
 1   first_name                           4000 non-null   object        
 2   last_name                            3875 non-null   object        
 3   gender                               4000 non-null   object        
 4   past_3_years_bike_related_purchases  4000 non-null   int64         
 5   DOB                                  3913 non-null   datetime64[ns]
 6   job_title                            3494 non-null   object        
 7   job_industry_category                3344 non-null   object        
 8   wealth_segment                       4000 non-null   object        
 9   deceased_indicator                   4000 non-null   object        
 10  default     

In [18]:
customer_demographic.isnull().sum()

customer_id                              0
first_name                               0
last_name                              125
gender                                   0
past_3_years_bike_related_purchases      0
DOB                                     87
job_title                              506
job_industry_category                  656
wealth_segment                           0
deceased_indicator                       0
default                                302
owns_car                                 0
tenure                                  87
dtype: int64

In [19]:
customer_demographic.duplicated().sum()

0

- We can see that the table consists of some missing values in certain columns : 

'last_name', 'DOB', 'job_title', 'job_industry_category', 'default', 'tenure'. There are no duplicate values. 

The default column seems to be unusual and should be checked in detail. The 'gender' column also seems to have inconsistent entires in it.

In [20]:
customer_demographic['default'].value_counts()

100                                       113
1                                         112
-1                                        111
-100                                       99
Ù¡Ù¢Ù£                                     53
                                         ... 
testâ testâ«                               31
/dev/null; touch /tmp/blns.fail ; echo     30
âªâªtestâª                                 29
ì¸ëë°í ë¥´                                 27
,ãã»:*:ã»ãâ( â» Ï â» )ãã»:*:ã»ãâ           25
Name: default, Length: 90, dtype: int64

In [21]:
customer_demographic['gender'].value_counts()

Female    2037
Male      1872
U           88
F            1
Femal        1
M            1
Name: gender, dtype: int64

In [22]:
customer_demographic = customer_demographic.drop('default', axis=1)

In [23]:
customer_demographic['gender'] = customer_demographic['gender'].replace('F','Female').replace('M','Male').replace('Femal','Female').replace('U','Unidentified')

In [24]:
customer_demographic.nunique()

customer_id                            4000
first_name                             3139
last_name                              3725
gender                                    3
past_3_years_bike_related_purchases     100
DOB                                    3448
job_title                               195
job_industry_category                     9
wealth_segment                            3
deceased_indicator                        2
owns_car                                  2
tenure                                   22
dtype: int64

In [25]:
customer_demographic['gender'].value_counts()

Female          2039
Male            1873
Unidentified      88
Name: gender, dtype: int64

In [26]:
customer_demographic['wealth_segment'].value_counts()

Mass Customer        2000
High Net Worth       1021
Affluent Customer     979
Name: wealth_segment, dtype: int64

In [27]:
customer_demographic['job_industry_category'].value_counts()

Manufacturing         799
Financial Services    774
Health                602
Retail                358
Property              267
IT                    223
Entertainment         136
Argiculture           113
Telecommunications     72
Name: job_industry_category, dtype: int64

In [28]:
customer_demographic['deceased_indicator'].value_counts()

N    3998
Y       2
Name: deceased_indicator, dtype: int64

In [29]:
customer_demographic['owns_car'].value_counts()

Yes    2024
No     1976
Name: owns_car, dtype: int64

# NEW_CUSTOMER LIST TABLE ANALYSIS:

In [30]:
new_customerlist = pd.read_excel(r"C:\\Users\\ASUS\\KPMG_VI_New_raw_data_update_final.xlsx", sheet_name='NewCustomerList',header=1)
new_customerlist.head(2)

first_name last_name gender  past_3_years_bike_related_purchases        DOB  \
0    Chickie   Brister   Male                                   86 1957-07-12   
1      Morly    Genery   Male                                   69 1970-03-22   

             job_title job_industry_category wealth_segment  \
0      General Manager         Manufacturing  Mass Customer   
1  Structural Engineer              Property  Mass Customer   

  deceased_indicator owns_car  ...  state    country  property_valuation  \
0                  N      Yes  ...    QLD  Australia                   6   
1                  N       No  ...    NSW  Australia                  11   

  Unnamed: 16 Unnamed: 17  Unnamed: 18  Unnamed: 19  Unnamed: 20  Rank  \
0        0.56        0.70       0.8750     0.743750            1     1   
1        0.89        0.89       1.1125     0.945625            1     1   

     Value  
0  1.71875  
1  1.71875  

[2 rows x 23 columns]

The raw data of the sheet "NewCustomerList" given here is read thorugh pandas and stored in a variable "new_customerlist".

In [31]:
new_customerlist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 23 columns):
 #   Column                               Non-Null Count  Dtype         
---  ------                               --------------  -----         
 0   first_name                           1000 non-null   object        
 1   last_name                            971 non-null    object        
 2   gender                               1000 non-null   object        
 3   past_3_years_bike_related_purchases  1000 non-null   int64         
 4   DOB                                  983 non-null    datetime64[ns]
 5   job_title                            894 non-null    object        
 6   job_industry_category                835 non-null    object        
 7   wealth_segment                       1000 non-null   object        
 8   deceased_indicator                   1000 non-null   object        
 9   owns_car                             1000 non-null   object        
 10  tenure       

- We find that the table data has some columns that are not necessaryy and they should be dropped : 

'Unnamed: 16',

'Unnamed: 17', 

'Unnamed: 18',

'Unnamed: 19', 

'Unnamed: 20'. 

- We also notice that there are some missing values in the table

In [32]:
new_customerlist = new_customerlist.drop(['Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19','Unnamed: 20'], axis=1)

In [33]:
new_customerlist.isnull().sum()

first_name                               0
last_name                               29
gender                                   0
past_3_years_bike_related_purchases      0
DOB                                     17
job_title                              106
job_industry_category                  165
wealth_segment                           0
deceased_indicator                       0
owns_car                                 0
tenure                                   0
address                                  0
postcode                                 0
state                                    0
country                                  0
property_valuation                       0
Rank                                     0
Value                                    0
dtype: int64

In [34]:
new_customerlist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                               Non-Null Count  Dtype         
---  ------                               --------------  -----         
 0   first_name                           1000 non-null   object        
 1   last_name                            971 non-null    object        
 2   gender                               1000 non-null   object        
 3   past_3_years_bike_related_purchases  1000 non-null   int64         
 4   DOB                                  983 non-null    datetime64[ns]
 5   job_title                            894 non-null    object        
 6   job_industry_category                835 non-null    object        
 7   wealth_segment                       1000 non-null   object        
 8   deceased_indicator                   1000 non-null   object        
 9   owns_car                             1000 non-null   object        
 10  tenure       

In [35]:
new_customerlist.nunique()

first_name                              940
last_name                               961
gender                                    3
past_3_years_bike_related_purchases     100
DOB                                     958
job_title                               184
job_industry_category                     9
wealth_segment                            3
deceased_indicator                        1
owns_car                                  2
tenure                                   23
address                                1000
postcode                                522
state                                     3
country                                   1
property_valuation                       12
Rank                                    324
Value                                   324
dtype: int64

In [36]:
new_customerlist['gender'].value_counts()

Female    513
Male      470
U          17
Name: gender, dtype: int64

In [38]:
new_customerlist['gender'] = new_customerlist['gender'].replace('U','Unidentified')

In [39]:
new_customerlist['gender'].value_counts()

Female          513
Male            470
Unidentified     17
Name: gender, dtype: int64

In [40]:
new_customerlist['state'].value_counts()

NSW    506
VIC    266
QLD    228
Name: state, dtype: int64

In [41]:
new_customerlist['wealth_segment'].value_counts()

Mass Customer        508
High Net Worth       251
Affluent Customer    241
Name: wealth_segment, dtype: int64

In [42]:
new_customerlist['job_industry_category'].value_counts()

Financial Services    203
Manufacturing         199
Health                152
Retail                 78
Property               64
IT                     51
Entertainment          37
Argiculture            26
Telecommunications     25
Name: job_industry_category, dtype: int64

# CUSTOMER ADDRESS TABLE ANALYSIS:

In [44]:
customer_address = pd.read_excel(r"C:\\Users\\ASUS\\KPMG_VI_New_raw_data_update_final.xlsx", sheet_name='CustomerAddress',header=1)
customer_address.head()

customer_id              address  postcode            state    country  \
0            1   060 Morning Avenue      2016  New South Wales  Australia   
1            2  6 Meadow Vale Court      2153  New South Wales  Australia   
2            4   0 Holy Cross Court      4211              QLD  Australia   
3            5  17979 Del Mar Point      2448  New South Wales  Australia   
4            6     9 Oakridge Court      3216              VIC  Australia   

   property_valuation  
0                  10  
1                  10  
2                   9  
3                   4  
4                   9

In [45]:
customer_address.shape

(3999, 6)

In [46]:
customer_address.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3999 entries, 0 to 3998
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   customer_id         3999 non-null   int64 
 1   address             3999 non-null   object
 2   postcode            3999 non-null   int64 
 3   state               3999 non-null   object
 4   country             3999 non-null   object
 5   property_valuation  3999 non-null   int64 
dtypes: int64(3), object(3)
memory usage: 187.6+ KB


In [47]:
customer_address.duplicated().sum()

0

In [48]:
customer_address['state'].value_counts()

NSW                2054
VIC                 939
QLD                 838
New South Wales      86
Victoria             82
Name: state, dtype: int64

In [49]:
customer_address['country'].value_counts()

Australia    3999
Name: country, dtype: int64

- The Customer Address Table is consisent and accurate. 

- It contains no missing data as well as no duplicated data in it. The table seems to contain all the customer address information about customers in Australia

- We can see that the 3 tables : the 'Customer Demographic' Table , the 'New Customer Lists' Table and the 'Customer Address' Table are relevant to each other, so it would be more meaningful to combine these tables and view them as one.

In [50]:
customer_demographic['customer_id'].iloc[-1]

4000

In [52]:
new_customerlist.insert(0, 'customer_id', range(4001, 4001 + len(new_customerlist)))

In [54]:
customer_demographic = pd.merge(customer_demographic, customer_address, on='customer_id', how='left')

In [55]:
customer_demographic.head()

customer_id      first_name  last_name  gender  \
0            1         Laraine  Medendorp  Female   
1            2             Eli    Bockman    Male   
2            3           Arlin     Dearle    Male   
3            4          Talbot        NaN    Male   
4            5  Sheila-kathryn     Calton  Female   

   past_3_years_bike_related_purchases        DOB               job_title  \
0                                   93 1953-10-12     Executive Secretary   
1                                   81 1980-12-16  Administrative Officer   
2                                   61 1954-01-20      Recruiting Manager   
3                                   33 1961-10-03                     NaN   
4                                   56 1977-05-13           Senior Editor   

  job_industry_category     wealth_segment deceased_indicator owns_car  \
0                Health      Mass Customer                  N      Yes   
1    Financial Services      Mass Customer                  N      Yes   
2              Property      Mass Customer                  N      Yes   
3                    IT      Mass Customer                  N       No   
4                   NaN  Affluent Customer                  N      Yes   

   tenure              address  postcode            state    country  \
0    11.0   060 Morning Avenue    2016.0  New South Wales  Australia   
1    16.0  6 Meadow Vale Court    2153.0  New South Wales  Australia   
2    15.0                  NaN       NaN              NaN        NaN   
3     7.0   0 Holy Cross Court    4211.0              QLD  Australia   
4     8.0  17979 Del Mar Point    2448.0  New South Wales  Australia   

   property_valuation  
0                10.0  
1                10.0  
2                 NaN  
3                 9.0  
4                 4.0

In [57]:
customer_demographic = customer_demographic.drop(['address','postcode','state','country','property_valuation'], axis=1)

In [59]:
new_customer_details = pd.concat([customer_demographic, new_customerlist], ignore_index=True, sort=False)

In [60]:
customer_demographic = new_customer_details

In [61]:
customer_demographic

customer_id      first_name  last_name  gender  \
0               1         Laraine  Medendorp  Female   
1               2             Eli    Bockman    Male   
2               3           Arlin     Dearle    Male   
3               4          Talbot        NaN    Male   
4               5  Sheila-kathryn     Calton  Female   
...           ...             ...        ...     ...   
4995         4996       Ferdinand  Romanetti    Male   
4996         4997            Burk    Wortley    Male   
4997         4998        Melloney      Temby  Female   
4998         4999          Dickie    Cubbini    Male   
4999         5000           Sylas    Duffill    Male   

      past_3_years_bike_related_purchases        DOB  \
0                                      93 1953-10-12   
1                                      81 1980-12-16   
2                                      61 1954-01-20   
3                                      33 1961-10-03   
4                                      56 1977-05-13   
...                                   ...        ...   
4995                                   60 1959-10-07   
4996                                   22 2001-10-17   
4997                                   17 1954-10-05   
4998                                   30 1952-12-17   
4999                                   56 1955-10-02   

                         job_title job_industry_category     wealth_segment  \
0              Executive Secretary                Health      Mass Customer   
1           Administrative Officer    Financial Services      Mass Customer   
2               Recruiting Manager              Property      Mass Customer   
3                              NaN                    IT      Mass Customer   
4                    Senior Editor                   NaN  Affluent Customer   
...                            ...                   ...                ...   
4995                     Paralegal    Financial Services  Affluent Customer   
4996        Senior Sales Associate                Health      Mass Customer   
4997  Budget/Accounting Analyst IV    Financial Services  Affluent Customer   
4998             Financial Advisor    Financial Services      Mass Customer   
4999           Staff Accountant IV              Property      Mass Customer   

     deceased_indicator owns_car  tenure                   address  postcode  \
0                     N      Yes    11.0                       NaN       NaN   
1                     N      Yes    16.0                       NaN       NaN   
2                     N      Yes    15.0                       NaN       NaN   
3                     N       No     7.0                       NaN       NaN   
4                     N      Yes     8.0                       NaN       NaN   
...                 ...      ...     ...                       ...       ...   
4995                  N       No     9.0               2 Sloan Way    2200.0   
4996                  N       No     6.0         04 Union Crossing    2196.0   
4997                  N      Yes    15.0  33475 Fair Oaks Junction    4702.0   
4998                  N      Yes    19.0        57666 Victoria Way    4215.0   
4999                  N      Yes    14.0        21875 Grover Drive    2010.0   

     state    country  property_valuation    Rank  Value  
0      NaN        NaN                 NaN     NaN    NaN  
1      NaN        NaN                 NaN     NaN    NaN  
2      NaN        NaN                 NaN     NaN    NaN  
3      NaN        NaN                 NaN     NaN    NaN  
4      NaN        NaN                 NaN     NaN    NaN  
...    ...        ...                 ...     ...    ...  
4995   NSW  Australia                 7.0   996.0  0.374  
4996   NSW  Australia                10.0   997.0  0.357  
4997   QLD  Australia                 2.0   997.0  0.357  
4998   QLD  Australia                 2.0   997.0  0.357  
4999   NSW  Australia                 9.0  1000.0  0.340  

[5000 rows x 19 columns]

# CONCLUSION:

### The given data is analysed and investigated in all aspects to inspect the Quality of data with respect to all qualities mentioned in the Data Quality Framework Table:

- Accuracy

- Completeness

- Uniqueness

- Validity

- Consistency

- Relevancy

- Timeliness

# THE END.